server:
  port: 8761
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: localhost
  server:
    renewal-percent-threshold: 0.49
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/
logging:
  level:
    com.netflix.eureka: 'off'
    com.netflix.discovery: 'off'