spring:
  application:
    name: order-service
  profiles:
    active: service1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: service1
server:
  port: 8881
---
spring:
  profiles: service2
server:
  port: 8882